### ISSUE TITLE
Cannot connect to server with GC 1.18.2 installed

### ISSUE THREAD

**Issue by Aylawoo** [GrowthcraftCE/Growthcraft-1.18#8]
Creating the issue referencing Discord converstaion.

Happening on a client and server running ONLY growthcraft.

Error on server connection attempt: https://i.imgur.com/ucEcbyI.png
Logs: https://gist.github.com/AylaCodes/4f69fc113c646faee2d458b193fe813c
The byte number it fails at appears to flip between 1, 2 and 3. 

Built from source with the included forge only a few deprecation warnings, singleplayer appears to work fine.

Was instructed to try with Patchouli installed - same results (Client and server, Singleplayer appears functional, multiplayer does not connect).

**Comment by Alatyami** [comment]
According to the errors, there is an issue with reading the recipe for making Cultured Milk in the Mixing Vat. Invalid byte usually indicates an issue with the file encoding, but I am not seeing any issues with that. 

https://github.com/GrowthcraftCE/Growthcraft-1.18/blob/release/src/main/resources/data/growthcraft_milk/recipes/mixing_vat_fluid_cultured_milk.json

**Comment by Aylawoo** [comment]
Fixed, thanks!
